# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# Commands to be run before your environment runs.
before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan migrate --force
  - php artisan db:seed --class DataSeeder --force
  - php artisan serve >/dev/null 2>&1 &

# Commands you want to run that will verify your build.
script: vendor/bin/phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always